import { flexRender, getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import { Check, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import api from '../api'
import Layout from '../components/Layout'
import Spinner from '../components/Spinner'

function getErrorMessage(error, fallback){ const data=error.response?.data; if(typeof data==='string')return data; if(Array.isArray(data))return data[0] || fallback; if(data&&typeof data==='object'){ for(const value of Object.values(data)){ if(Array.isArray(value)&&value[0])return value[0]; if(typeof value==='string')return value } } return fallback }
function Table({ data, columns }){ const [globalFilter,setGlobalFilter]=useState(''); const table=useReactTable({data,columns,state:{globalFilter},onGlobalFilterChange:setGlobalFilter,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),getFilteredRowModel:getFilteredRowModel()}); return <><input className="input mb-3" placeholder="Filtrar por texto..." value={globalFilter} onChange={e=>setGlobalFilter(e.target.value)}/><div className="overflow-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50">{table.getHeaderGroups().map(h=><tr key={h.id}>{h.headers.map(x=><th className="cursor-pointer px-4 py-3 text-left" onClick={x.column.getToggleSortingHandler()} key={x.id}>{flexRender(x.column.columnDef.header,x.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr className="border-t" key={r.id}>{r.getVisibleCells().map(c=><td className="px-4 py-3" key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div></> }
export default function Admin(){ const [vehiculos,setVehiculos]=useState([]),[ingresos,setIngresos]=useState([]),[loading,setLoading]=useState(true),[motivos,setMotivos]=useState({}); const load=async()=>{setLoading(true); const [v,i]=await Promise.all([api.get('/vehiculos/'),api.get('/ingresos/')]); setVehiculos(v.data); setIngresos(i.data); setLoading(false)}; useEffect(()=>{Promise.resolve().then(load).catch(()=>toast.error('No se pudo cargar admin'))},[]); const resolver=async(id,aprobar)=>{const motivo_rechazo=motivos[id]; if(!aprobar&&!motivo_rechazo)return toast.error('Ingresa el motivo de rechazo'); try{await api.post(`/vehiculos/${id}/resolver/`,{aprobar,motivo_rechazo}); toast.success(aprobar?'Vehículo aprobado':'Vehículo rechazado'); load()}catch(error){toast.error(getErrorMessage(error,'No se pudo resolver la solicitud'))}}; const pendientes=vehiculos.filter(v=>v.estado==='pendiente'); const cols=useMemo(()=>[{header:'Patente',accessorKey:'patente'},{header:'Propietario',accessorKey:'propietario'},{header:'Acciones',cell:i=><div className="flex flex-wrap gap-2"><button onClick={()=>resolver(i.row.original.id,true)} className="btn-ok"><Check size={16}/> Aprobar</button><input className="input max-w-48" placeholder="Motivo rechazo" onChange={e=>setMotivos(m=>({...m,[i.row.original.id]:e.target.value}))}/><button onClick={()=>resolver(i.row.original.id,false)} className="btn-danger"><X size={16}/> Rechazar</button></div>}], [motivos]); const ingresoCols=useMemo(()=>[{header:'Fecha',accessorKey:'timestamp',cell:i=>i.getValue()?format(parseISO(i.getValue()),'PPp',{locale:es}):''},{header:'Tipo',accessorKey:'tipo'},{header:'Valor',accessorKey:'valor_ingresado'},{header:'Resultado',accessorKey:'resultado'}],[]); if(loading)return <Layout><Spinner/></Layout>; return <Layout><div className="space-y-6"><section className="card"><h1 className="mb-4 text-2xl font-bold">Solicitudes pendientes</h1><Table data={pendientes} columns={cols}/></section><section className="card"><h1 className="mb-4 text-2xl font-bold">Historial de ingresos</h1><Table data={ingresos} columns={ingresoCols}/></section></div></Layout> }
