import { CheckCircle2, XCircle } from 'lucide-react'
import { useState } from 'react'
import toast from 'react-hot-toast'
import api from '../api'
import Layout from '../components/Layout'
import CameraCapture from '../components/CameraCapture'
import Spinner from '../components/Spinner'

const rutOk = (v) => /^\d{7,8}-[\dkK]$/.test(v)
const patenteOk = (v) => /^([A-Z]{4}\d{2}|[A-Z]{2}\d{4})$/.test(v)
function Result({ ok, title, details }) { if (ok === null) return null; return <div className={`mt-5 rounded-3xl p-8 text-center text-white shadow-xl ${ok ? 'bg-emerald-600' : 'bg-red-600'}`}>{ok ? <CheckCircle2 className="mx-auto" size={72}/> : <XCircle className="mx-auto" size={72}/>}<h2 className="mt-3 text-4xl font-black">{title}</h2><p className="mt-2 text-2xl">{details}</p></div> }
export default function Guardia(){ const [rut,setRut]=useState(''),[patente,setPatente]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false); const verificarRut=async()=>{ if(!rutOk(rut))return toast.error('RUT inválido'); setLoading(true); try{const {data}=await api.post('/guardia/verificar-rut/',{rut}); setResult({ok:data.permitido,title:data.permitido?'VISITA AUTORIZADA':'VISITA RECHAZADA',details:data.permitido?`${data.nombre} · Unidad ${data.unidad}`:'RUT sin visita vigente'}); toast[data.permitido?'success':'error'](data.permitido?'Visita vigente':'Visita no autorizada')}finally{setLoading(false)} }; const leerFoto=async(foto)=>{ if(!foto)return; const fd=new FormData(); fd.append('foto',foto); setLoading(true); try{const {data}=await api.post('/ocr/leer-patente/',fd); if(data.ok){setPatente(data.patente); toast.success('Patente detectada')} else {toast.error(data.detalle || 'No se pudo leer la patente')}}finally{setLoading(false)} }; const verificarPatente=async()=>{ const p=patente.toUpperCase(); if(!patenteOk(p))return toast.error('Patente inválida'); setLoading(true); try{const {data}=await api.post('/guardia/verificar-patente/',{patente:p}); setResult({ok:data.permitido,title:data.permitido?'VEHÍCULO AUTORIZADO':'VEHÍCULO RECHAZADO',details:data.permitido?`Unidad ${data.unidad}`:'Patente no aprobada'}); toast[data.permitido?'success':'error'](data.permitido?'Patente aprobada':'Patente rechazada')}finally{setLoading(false)} }; return <Layout><div className="mx-auto max-w-xl space-y-5"><h1 className="text-center text-3xl font-black">Control de acceso</h1><section className="card space-y-4"><h2 className="text-2xl font-bold">Verificar visita</h2><input className="input h-14 text-xl" placeholder="12345678-9" value={rut} onChange={e=>setRut(e.target.value)}/><button disabled={loading} onClick={verificarRut} className="btn-primary h-16 w-full text-xl disabled:opacity-50">Verificar RUT</button></section><section className="card space-y-4"><h2 className="text-2xl font-bold">Verificar vehículo</h2><CameraCapture onCapture={leerFoto}/><input className="input h-14 text-xl uppercase" placeholder="AABB11 o AA1111" value={patente} onChange={e=>setPatente(e.target.value.toUpperCase())}/><button disabled={loading} onClick={verificarPatente} className="btn-primary h-16 w-full text-xl disabled:opacity-50">Confirmar patente</button></section>{loading ? <Spinner text="Procesando..."/> : <Result {...(result || {ok:null})}/>}</div></Layout> }
