import { Car, Trash2 } from 'lucide-react'
import { useMemo } from 'react'
import Table from '../../components/Table'
import VehiculoForm from './VehiculoForm'
export default function VehiculosPanel({ vehiculos }) {
  const active = vehiculos.page.results.filter(vehicle => ['pendiente', 'aprobado'].includes(vehicle.estado)).length; const limit = vehiculos.estacionamientos?.limite_patentes; const known = Number.isFinite(limit); const reached = known && active >= limit; const spaces = Array.isArray(vehiculos.estacionamientos?.estacionamientos) ? vehiculos.estacionamientos.estacionamientos : []
  const columns = useMemo(() => [{ header: 'Patente', accessorKey: 'patente' }, { header: 'Estado', cell: info => <span title={info.row.original.motivo_rechazo || ''} className={info.row.original.estado === 'aprobado' ? 'badge-green' : info.row.original.estado === 'rechazado' ? 'badge-red' : 'badge-yellow'}>{info.row.original.estado}</span> }, { header: 'Acciones', cell: info => { const processing = vehiculos.eliminando === info.row.original.id; return <button type="button" className="btn-danger disabled:opacity-50" disabled={processing} onClick={() => vehiculos.eliminar(info.row.original.id)}><Trash2 size={15}/> {processing ? 'Procesando...' : 'Eliminar'}</button> } }], [vehiculos])
  return <section id="panel-vehiculos" role="tabpanel" aria-labelledby="tab-vehiculos" className="card"><h2 className="section-title"><Car/> Vehículos</h2>{known && (spaces.length > 0 ? <p className="mb-3 text-sm text-slate-600">Tienes {spaces.length} {spaces.length === 1 ? 'estacionamiento' : 'estacionamientos'} ({spaces.join(', ')}) — puedes registrar hasta {limit} {limit === 1 ? 'vehículo' : 'vehículos'}.</p> : <p className="mb-3 text-sm text-red-600">No tienes estacionamientos asignados — no puedes registrar vehículos. Contacta al administrador.</p>)}<VehiculoForm form={vehiculos.form} onSubmit={vehiculos.crear} disabled={reached}/>{reached && limit > 0 && <p className="mt-2 text-sm text-red-600">Ya alcanzaste el límite de {limit} {limit === 1 ? 'patente pendiente o aprobada' : 'patentes pendientes o aprobadas'}.</p>}<div className="mt-5"><Table {...vehiculos.page} data={vehiculos.page.results} onPrevious={() => vehiculos.fetchPage(vehiculos.page.previous)} onNext={() => vehiculos.fetchPage(vehiculos.page.next)} columns={columns} emptyMessage="No hay vehículos registrados."/></div></section>
}
