import { format, formatDistanceToNowStrict, isAfter, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import { Mail, QrCode, Trash2, UserPlus, X } from 'lucide-react'
import { useMemo } from 'react'
import Table from '../../components/Table'
import { documentTypes } from './schemas'
import VisitanteForm from './VisitanteForm'
export default function VisitasPanel({ visitas, showReminder, dismissReminder, openProfile }) {
  const columns = useMemo(() => [{ header: 'Nombre', accessorKey: 'nombre' }, { header: 'Tipo de documento', accessorKey: 'tipo_documento', cell: info => documentTypes.find(type => type.value === info.getValue())?.label || info.getValue() || '—' }, { header: 'Número de documento', accessorKey: 'numero_documento' }, { header: 'País', accessorKey: 'pais_documento', cell: info => info.getValue() || '—' }, { header: 'Vigente hasta', accessorKey: 'fecha_fin', cell: info => info.getValue() ? `${format(parseISO(info.getValue()), 'PPp', { locale: es })} (${formatDistanceToNowStrict(parseISO(info.getValue()), { locale: es, addSuffix: true })})` : <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold uppercase text-blue-700">Permanente</span> }, { header: 'Estado', cell: info => { const permanent = info.row.original.fecha_fin == null; const stored = info.row.original.estado; const active = permanent || (stored ? ['vigente', 'activo', 'autorizado'].includes(stored.toLowerCase()) : isAfter(parseISO(info.row.original.fecha_fin), new Date())); return <span className={active ? 'badge-green' : 'badge-gray'}>{permanent ? 'vigente' : stored || (active ? 'vigente' : 'expirada')}</span> } }, { header: 'Acciones', cell: info => { const processing = visitas.eliminando === info.row.original.id; return <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" disabled={!info.row.original.token_qr || processing} onClick={() => visitas.setQrVisitor(info.row.original)} title={!info.row.original.token_qr ? 'Esta visita no tiene un código QR' : ''}><QrCode size={17}/> Ver QR</button><button type="button" className="btn-danger disabled:opacity-50" disabled={processing} onClick={() => visitas.eliminar(info.row.original.id)}><Trash2 size={15}/> {processing ? 'Procesando...' : 'Eliminar'}</button></div> } }], [visitas])
  return <section id="panel-visitas" role="tabpanel" aria-labelledby="tab-visitas" className="card">{showReminder && <div className="mb-5 flex items-center gap-3 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-blue-900" role="status"><Mail className="shrink-0" size={20}/><p className="grow text-sm"><span className="font-bold">Completa tus datos de contacto.</span>{' '}Ayuda a la administración a comunicarse contigo ante una emergencia.</p><button type="button" className="shrink-0 font-bold text-[#317fcf] underline underline-offset-2 hover:text-blue-800" onClick={openProfile}>Ir a Mi Perfil</button><button type="button" className="shrink-0 rounded-md p-1 text-blue-700 hover:bg-blue-100" onClick={dismissReminder} aria-label="Descartar recordatorio"><X size={18}/></button></div>}<h2 className="section-title"><UserPlus/> Visitantes</h2><VisitanteForm form={visitas.form} onSubmit={visitas.crear}/><div className="mt-5"><Table {...visitas.page} data={visitas.page.results} onPrevious={() => visitas.fetchPage(visitas.page.previous)} onNext={() => visitas.fetchPage(visitas.page.next)} columns={columns} emptyMessage="No hay visitantes registrados."/></div></section>
}
