import { format, formatDistanceToNowStrict } from 'date-fns'
import { es } from 'date-fns/locale'
import { formatearDocumento } from '../../utils/documento'
import { documentTypes } from './schemas'
const ahoraLocal = () => { const ahora = new Date(); ahora.setMinutes(ahora.getMinutes() - ahora.getTimezoneOffset()); return ahora.toISOString().slice(0, 16) }
export default function VisitanteForm({ form, onSubmit }) {
  const documentType = form.watch('tipo_documento'); const visitorType = form.watch('tipo_visita'); const endDate = form.watch('fecha_fin'); const registration = form.register('numero_documento')
  return <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-3 md:grid-cols-2">
    <div><label className="mb-1 block text-sm font-medium" htmlFor="visitor-document-type">Tipo de documento</label><select id="visitor-document-type" className="input w-full" {...form.register('tipo_documento')} onChange={event => { form.setValue('tipo_documento', event.target.value); if (event.target.value === 'rut') form.setValue('pais_documento', '') }}>{documentTypes.map(type => <option key={type.value} value={type.value}>{type.label}</option>)}</select></div>
    <div><label className="mb-1 block text-sm font-medium" htmlFor="visitor-document-number">Número de documento</label><input id="visitor-document-number" className={`input h-14 w-full text-lg ${documentType !== 'rut' ? 'uppercase' : ''}`} placeholder={documentType === 'rut' ? '12.345.678-5' : 'PA123456'} {...registration} onBlur={event => { event.target.value = formatearDocumento(documentType, event.target.value); registration.onChange(event); registration.onBlur(event) }}/>{form.formState.errors.numero_documento && <p className="mt-1 text-sm text-red-600">{form.formState.errors.numero_documento.message}</p>}</div>
    {documentType !== 'rut' && <div><label className="mb-1 block text-sm font-medium" htmlFor="visitor-document-country">País emisor (opcional)</label><input id="visitor-document-country" className="input w-full" placeholder="Ej.: Perú" {...form.register('pais_documento')}/>{form.formState.errors.pais_documento && <p className="mt-1 text-sm text-red-600">{form.formState.errors.pais_documento.message}</p>}</div>}
    <div><label className="mb-1 block text-sm font-medium" htmlFor="visitor-name">Nombre</label><input id="visitor-name" className="input w-full" placeholder="Nombre" {...form.register('nombre')}/>{form.formState.errors.nombre && <p className="mt-1 text-sm text-red-600">{form.formState.errors.nombre.message}</p>}</div>
    <fieldset className="md:col-span-2"><legend className="mb-2 text-sm font-medium">Tipo de visita</legend><div className="grid gap-2 sm:grid-cols-2">{[{ value: 'temporal', title: 'Visita temporal', description: 'El QR vence cuando elijas; sin fecha, dura 5 horas desde ahora.' }, { value: 'permanente', title: 'Visita permanente', description: 'El QR no vence. Ideal para familiares, nana o cuidador.' }].map(option => <label key={option.value} className={`cursor-pointer rounded-xl border p-3 transition ${visitorType === option.value ? 'border-[#4696e5] bg-blue-50 text-blue-900 ring-1 ring-[#4696e5]' : 'border-slate-200 hover:bg-slate-50'}`}><input className="sr-only" type="radio" value={option.value} {...form.register('tipo_visita')}/><span className="block font-bold">{option.title}</span><span className="mt-1 block text-sm">{option.description}</span></label>)}</div></fieldset>
    {visitorType === 'temporal' && <div className="md:col-span-2"><label className="mb-1 block text-sm font-medium" htmlFor="fecha-fin">Vigente hasta (opcional)</label><input id="fecha-fin" className="input w-full" type="datetime-local" min={ahoraLocal()} {...form.register('fecha_fin')}/>{form.formState.errors.fecha_fin && <p className="mt-1 text-sm text-red-600">{form.formState.errors.fecha_fin.message}</p>}</div>}
    <p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800 md:col-span-2">{visitorType === 'permanente' ? 'Este QR no vence. Puedes eliminar la visita cuando ya no la necesites.' : endDate ? `Vence el ${format(new Date(endDate), "d 'de' MMMM 'a las' HH:mm", { locale: es })} — ${formatDistanceToNowStrict(new Date(endDate), { locale: es, addSuffix: true })}.` : 'Sin fecha, el QR vence 5 horas después de crear la visita.'}</p>
    <button className="btn-primary h-14 md:col-span-2">Crear visitante</button>
  </form>
}
