import { useCallback, useState } from 'react'
import toast from 'react-hot-toast'
import api, { getApiErrorMessage } from '../../../api'
import { documentoEsValido } from '../../../utils/documento'
import { MENSAJE_FORMATO_PATENTE, normalizarPatente, patenteEsValida } from '../../../utils/patente'
const visitDetails = details => <><span className="block text-2xl font-bold sm:text-3xl">{details.name}</span><span className="mt-1 block text-2xl font-bold sm:text-3xl">Unidad {details.unit}</span><span className="mt-2 block text-lg sm:text-xl">{details.validity}</span></>
const residentDetails = details => <><span className="block text-2xl font-bold sm:text-3xl">{details.name}</span><span className="mt-1 block text-2xl font-bold sm:text-3xl">Unidad {details.unit}</span></>
export const authorizationDetails = authorization => ({ name: authorization.nombre || authorization.visitante?.nombre || 'Visitante', unit: authorization.unidad || authorization.departamento || authorization.unidad_destino || '—', validity: authorization.vigencia || authorization.fecha_fin || authorization.vigente_hasta || 'Vigencia no informada' })
const authorizationsFrom = data => Array.isArray(data) ? data : Array.isArray(data?.autorizaciones) ? data.autorizaciones : Array.isArray(data?.results) ? data.results : data?.permitido ? [data] : []
export default function useVerificacionAcceso() {
  const [document, setDocument] = useState({ tipo_documento: 'rut', numero_documento: '', pais_documento: '' }); const [patente, setPatente] = useState(''); const [results, setResults] = useState({ visita: null, vehiculo: null }); const [authorizations, setAuthorizations] = useState([]); const [selectedAuthorizationId, setSelectedAuthorizationId] = useState(null); const [loading, setLoading] = useState(false); const [scanning, setScanning] = useState(false)
  const clearVisit = () => { setAuthorizations([]); setSelectedAuthorizationId(null); setResults(current => ({ ...current, visita: null })) }
  const updateDocument = (field, value) => { setDocument(current => ({ ...current, [field]: value, ...(field === 'tipo_documento' && value === 'rut' ? { pais_documento: '' } : {}) })); clearVisit() }
  const verificarDocumento = async () => { const number = document.numero_documento.trim().toUpperCase(); if (!documentoEsValido(document.tipo_documento, number)) return toast.error('Ingresa un número de documento válido'); const payload = { tipo_documento: document.tipo_documento, numero_documento: number }; if (document.tipo_documento !== 'rut' && document.pais_documento.trim()) payload.pais_documento = document.pais_documento.trim(); setLoading(true); clearVisit(); try { const { data } = await api.post('/guardia/verificar-documento/', payload); const matches = authorizationsFrom(data); if (!matches.length) { setResults(current => ({ ...current, visita: { status: 'rejected', title: 'VISITA NO AUTORIZADA', details: data?.detalle || 'No hay autorizaciones vigentes' } })); toast.error('Visita no autorizada') } else if (matches.length === 1) { selectAuthorization(matches[0]); toast.success('Visita vigente') } else { setAuthorizations(matches); toast('Selecciona la unidad de destino') } } catch (error) { setVisitError(error, 'No se pudo verificar la visita') } finally { setLoading(false) } }
  const setVisitError = (error, fallback) => { const network = !error.response; setResults(current => ({ ...current, visita: { status: network ? 'network' : 'server', title: network ? 'ERROR DE RED' : 'ERROR DEL SERVIDOR', details: getApiErrorMessage(error, network ? 'Revisa la conexión e intenta nuevamente' : fallback) } })) }
  const selectAuthorization = authorization => { setSelectedAuthorizationId(authorization.id); setResults(current => ({ ...current, visita: { status: 'authorized', title: 'VISITA AUTORIZADA', details: visitDetails(authorizationDetails(authorization)) } })) }
  const verificarQr = useCallback(async token => { setScanning(false); setLoading(true); clearVisit(); try { const { data } = await api.post('/guardia/verificar-qr/', { token }); const allowed = data.permitido ?? data.autorizado ?? false; const details = authorizationDetails(data); const resident = allowed && data.tipo === 'residente'; setResults(current => ({ ...current, visita: { status: allowed ? 'authorized' : 'rejected', title: allowed ? (resident ? 'RESIDENTE AUTORIZADO' : 'VISITA AUTORIZADA') : 'VISITA NO AUTORIZADA', details: allowed ? (resident ? residentDetails(details) : visitDetails(details)) : (data.detalle || 'El código no está vigente') } })); toast[allowed ? 'success' : 'error'](allowed ? (resident ? 'Residente autorizado' : 'Visita vigente') : 'Visita no autorizada') } catch (error) { const network = !error.response; const denied = error.response && [400, 403, 404].includes(error.response.status); setResults(current => ({ ...current, visita: { status: denied ? 'rejected' : network ? 'network' : 'server', title: denied ? 'VISITA NO AUTORIZADA' : network ? 'ERROR DE RED' : 'ERROR DEL SERVIDOR', details: getApiErrorMessage(error, denied ? 'El código no es válido o ya expiró' : network ? 'Revisa la conexión e intenta nuevamente' : 'No se pudo verificar el código') } })) } finally { setLoading(false) } }, [])
  const leerFoto = async foto => { if (!foto) return; const fd = new FormData(); fd.append('foto', foto); setLoading(true); try { const { data } = await api.post('/ocr/leer-patente/', fd); if (data.ok) { setPatente(normalizarPatente(data.patente)); toast.success('Patente detectada') } else toast.error(data.detalle || 'No se pudo leer la patente') } finally { setLoading(false) } }
  const verificarPatente = async () => { const normalized = normalizarPatente(patente); if (!patenteEsValida(normalized)) return toast.error(MENSAJE_FORMATO_PATENTE); setLoading(true); try { const { data } = await api.post('/guardia/verificar-patente/', { patente: normalized }); setResults(current => ({ ...current, vehiculo: { status: data.permitido ? 'authorized' : 'rejected', title: data.permitido ? 'VEHÍCULO AUTORIZADO' : 'VEHÍCULO RECHAZADO', details: data.permitido ? `Unidad ${data.unidad}` : 'Patente no aprobada' } })); toast[data.permitido ? 'success' : 'error'](data.permitido ? 'Patente aprobada' : 'Patente rechazada') } finally { setLoading(false) } }
  return { document, patente, setPatente, results, setResults, authorizations, selectedAuthorizationId, loading, scanning, setScanning, updateDocument, verificarDocumento, selectAuthorization, verificarQr, leerFoto, verificarPatente }
}
